/* CURRENT (recorded engine 1.0.0 baseline) vs NEW (engine in js/) → docs/GATE-3-REGRESSION.md */
const fs = require('fs');
const path = require('path');
const C = require('../js/calc.js');
const V = require('../js/vent.js');
const version = require('../js/core/version.js');
const base = require('../tests/fixtures/baseline-v1.json');
const { cases, ventCases } = require('../tests/baseline-cases.js');
const { snapshotRoom, snapshotVent } = require('../tests/snapshot.js');

const rows = []; let diffs = 0;
for (const [k, f] of Object.entries(cases)) {
  const p = f();
  p.rooms.forEach((r, i) => {
    const now = snapshotRoom(r, C.calcRoom(r, p)), old = base.rooms[k][i];
    const same = JSON.stringify(now) === JSON.stringify(old);
    if (!same) diffs++;
    rows.push(`| ${k} | ${r.name} | ${old.capacity.toFixed(3)} | ${now.capacity.toFixed(3)} | ${(now.capacity - old.capacity).toFixed(6)} | ${same ? 'identical (all components)' : '**DIFFERENT**'} |`);
  });
}
for (const [k, f] of Object.entries(ventCases)) {
  const now = snapshotVent(V.calcMachineryRoom(f())), old = base.vent[k];
  const same = JSON.stringify(now) === JSON.stringify(old); if (!same) diffs++;
  rows.push(`| ${k} | emergency m³/h | ${old.emergency.toFixed(1)} | ${now.emergency.toFixed(1)} | ${(now.emergency - old.emergency).toFixed(6)} | ${same ? 'identical (all modes)' : '**DIFFERENT**'} |`);
}
const md = `# Gate 3 — Regression: CURRENT (engine 1.0.0) vs NEW (engine ${version.ENGINE_VERSION})

Generated by \`node tools/compare-engines.js\` on ${new Date().toISOString().slice(0, 10)}. CURRENT = results recorded from engine 1.0.0 (\`tests/fixtures/baseline-v1.json\`); NEW = engine ${version.ENGINE_VERSION} with **default options**. Every load component, surface, product, door, air-change value, SST and capacity is compared, not only the totals.

**Result: ${diffs === 0 ? 'no differences in any case' : diffs + ' case(s) differ'}.**

| Case | Room / quantity | CURRENT [kW] | NEW [kW] | Δ | Components |
|---|---|---:|---:|---:|---|
${rows.join('\n')}

## Option cases (differences are intended and match the approved hand calculations)

| Item | Case | CURRENT | NEW (option on) | Hand calculation (Gate 3 doc) |
|---|---|---:|---:|---:|
| G3-1 | Base load −75.7 kWh/day, fan 8 % | fans −6.06 kWh/day | 0 | 0 |
| G3-2 | Chiller, 12 h pull-down, “rate over pull-down” | 25.099 kW | 22.891 kW | 22.89 kW |
| G3-2 | Chiller, 24 h pull-down | 20.231 kW | 20.231 kW | identical |
| G3-3 | Chiller, wall to −25 °C, “no credit” | 17.813 kW | 18.891 kW | 18.89 kW |
| G3-4 | Beef, entered h_if 233, c_p 3.2 / 1.7 | Siebel | entered values used | q = 3.2·11.7 + 233 + 1.7·16.3 |
| G3-5 | Apples 60 t/day, w_in 30 W/t | — | +43.2 kWh/day | +43.2 kWh/day |

Verified automatically by \`tests/regression.test.js\` (defaults) and \`tests/gate3.test.js\` (options).
`;
fs.writeFileSync(path.join(__dirname, '..', 'docs', 'GATE-3-REGRESSION.md'), md);
console.log(`Compared ${rows.length} results; differences: ${diffs}`);
